version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    environment:
      - ADMINER_DESIGN=flat
    ports:
      - 8081:8080
