swagger: '2.0'

info:
  title: Settings Store
  version: 1.0.0

paths:
  /settings:
    get:
      summary: Get all settings
      operationId: getAllSettings
      responses:
        '200':
          description: Settings retrieved successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/Setting'
      produces:
        - application/json
    post:
      summary: Add new setting
      operationId: addSetting
      responses:
        '201':
          description: Settings added successfully
      parameters:
        - description: Setting to add
          required: true
          name: setting
          in: body
          schema:
            $ref: '#/definitions/Setting'
      consumes:
        - application/json

  /settings/{id}:
    get:
      summary: Get a setting
      operationId: getSetting
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the setting to get
          type: integer
      responses:
        '200':
          description: Setting retrieved successfully
          schema:
            $ref: '#/definitions/Setting'
        '404':
          description: Setting does not exist
      produces:
        - application/json
    put:
      summary: Update existing setting
      operationId: updateSetting
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the setting to get
          type: integer
        - description: Setting to update
          required: true
          name: setting
          in: body
          schema:
            $ref: '#/definitions/Setting'
      responses:
        '204':
          description: Setting updated successfully
        '404':
          description: Setting does not exist
      consumes:
        - application/json
    delete:
      summary: Remove existing setting
      operationId: removeSetting
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the setting to remove
          type: integer
      responses:
        '204':
          description: Setting removed successfully
        '404':
          description: Setting does not exist
      consumes:
        - application/json

definitions:
  Setting:
    type: object
    properties:
      id:
        type: integer
        minimum: 0
        maximum: 16
      type:
        type: string
        enum: [global, local, temporary, default]
      value:
        type: string
        minLength: 1
        maxLength: 32
      end:
        $ref: '#/definitions/DateTime'
    required:
      - id
      - type
      - value
      - end
  DateTime:
    type: string
    format: date-time
    x-go-type:
      type: Time
      import:
        package: time
      embedded: true
